### ISSUE TITLE
Feed Policy and the Mapbox blog

### ISSUE THREAD

**Issue by imagico** [gravitystorm/blogs.osm.org#18]
It is nice to see the blogs being overhauled and a transparent policy regarding feeds being added.

The Mapbox blog IMO however stretches this quite a bit.  Certainly there are quite a few entries there which are OSM related but there is not really a need to have the latest hires or the latest products or customer projects featured on blogs.openstreetmap.org.

Since the Mapbox blog has tags shown on the website and they have an OpenStreetMap tag it might be possible to simply ask them to provide a tag specific feed.

**Comment by gravitystorm** [comment]
A tag-specific feed would be the best option. @imagico could you ask them and let us know the results please?

**Comment by imagico** [comment]
Since i have no specific contacts within Mapbox for this kind of thing i am just going to cc @planemad and @mikelmaron who served as community contacts in the past - the matter is if Mapbox can provide a tag specific feed for the [Mapbox blog](https://www.mapbox.com/blog/) for more selective inclusion on [blogs.openstreetmap.org](https://blogs.openstreetmap.org/).

**Comment by mikelmaron** [comment]
Thanks for checking in on this -- this is best -- https://www.mapbox.com/blog/tags/openstreetmap/

**Comment by tomhughes** [comment]
@mikelmaron sure - the question is whether there is (or could be) an RSS feed for that tag?

**Comment by smsm1** [comment]
@mikelmaron is there an RSS/Atom feed for just the tag? Looking at the source of the page the only RSS is for the full blog i.e.  `<link rel='alternate' type='application/rss+xml' title='RSS' href='https://www.mapbox.com/blog/blog.rss' />`

**Comment by mikelmaron** [comment]
@tomhughes @smsm1 not at the moment. checking what it would take

**Comment by geraldb** [comment]
FYI: First thanks for using Pluto. I'm the author / dev of pluto ;-)   As an alternative you might use / add an includes filter with keywords to the config. Example:

    markotto:
      title: Mark Otto @ San Francisco, CA › United States
      link: http://markdotto.com
      feed: http://feeds.feedburner.com/mdo
      includes: Jekyll|GitHub Pages|Poole|Hyde|Lanyon

In this case the keywords for includes might be  openstreetmap|osm or something. Cheers.

**Comment by mikelmaron** [comment]
If @geraldb suggestion works, great. Turns out to be a bit of a rabbit hole to build RSS feed of tags. Willing to look into it, but don't have a lot of extra time.

You'd only need to filter for "OpenStreetMap". Our blog posts check for and only permit this way of writing it.

**Comment by harry-wood** [comment]
Trouble is a filter for posts mentioning "openstreetmap" would skip over a few things which might be interesting e.g. [this one about data (from OpenStreetMap!) feeding into unity games](https://www.mapbox.com/blog/motive-game/ ). I suppose it might help motivate Mapbox to mention OpenStreetMap more!

To be honest I'm not sure this issue is an issue. I don't see anything on the Mapbox blog which is _very_ irrelevant to OSMers. The frequent hiring blog posts maybe, but even then. Knowing that the largest company working with OSM data has hired someone new (and knowing how often they're doing this and in which kinds of positions in which regions) is not entirely irrelevant to OpenStreetMappers. Not irrelevant in the same way as it would be if we piped in non-maps-category posts from [my own blog](http://harrywood.co.uk/blog/) for example (lucky wordpress has per-category feeds)

It's good to know about this filter technique though. I suppose we might use that to spread the net quite wide, pulling in lots of geo industry blogs, and just filtering for "openstreetmap" (we _might_, but then again. Lots of feeds. Lots of filters. could get messy)

**Comment by imagico** [comment]
From my side this was mainly about policy.  If the Mapbox blog is accepted in full other companies using OpenStreetMap might rightfully ask for being included as well.  There should be some kind of policy for that.

Regarding keyword filtering - as i see it Mapbox already tags OSM related post with an openstreetmap tag - we just don't get a tag based feed.  So the argument about missing OSM related posts with no mentioning of OpenStreetMap in the text does not seem convincing to me - unless Mapbox misses to tag them as such - which is not really our problem (and which they likely won't if they know we filter based on this).

**Comment by systemed** [comment]
Perhaps worth revisiting the filter idea?

I like finding out what Mapbox is doing (which is why I follow them on Twitter, for example), and appreciate that they've recently stepped up their blogging now they've moved to Medium (https://blog.mapbox.com/). That said, a significant number of posts now have little or tangential OSM relevance; and because they tend to be written in an engaging image-heavy style, they can overwhelm the display at blogs.osm.org.

**Comment by gravitystorm** [comment]
@systemed I was thinking just the same thing earlier today. Given there's no progress on the tag-specific feed approach, we should filter based on "OpenStreetMap" as a workaround. I'll happily approve a PR from anyone who wants to make one.

**Comment by mikelmaron** [comment]
medium has an RSS feed just for openstreetmap tagged posts https://blog.mapbox.com/feed/tagged/openstreetmap/

**Comment by mikelmaron** [comment]
does this PR do it? https://github.com/gravitystorm/blogs.osm.org/pull/31

**Comment by tomhughes** [comment]
Closed by #31.

**Comment by systemed** [comment]
Superb - thanks @mikelmaron.
