### ISSUE TITLE
Problem with images and large gaps

### ISSUE THREAD

**Issue by gravitystorm** [gravitystorm/blogs.osm.org#19]
in #8 @yvecai reported:

> Images are now pushed down under the right feed list, leaving a long blank on the first post.

**Comment by tomhughes** [comment]
I did play with it the other day - if we just want to fix the images then something like `max-width: calc(100% - 180px)` should do it although we may want a fallback for older browsers.

I'm tempted to say the left hand column should just have a 200px right margin though so that it doesn't widen out below the left navbar. That's slightly tricky because there's no wrapper for the left column so when prototyping from the DOM inspector I had to apply it to three or four different items.

**Comment by harry-wood** [comment]
We've got another wide image near the top right now causing the large gap problem:

![screen shot 2017-02-24 at 17 48 26](https://cloud.githubusercontent.com/assets/227525/23314371/9c294c56-fab9-11e6-8fa2-ba6e10d9831c.png)

I have done a fix https://github.com/gravitystorm/blogs.osm.org/pull/21  following @tomhughes 's  _"so that it doesn't widen out below the right navbar"_ suggestion
