### ISSUE TITLE
Add requested feeds

### ISSUE THREAD

**Issue by smsm1** [gravitystorm/blogs.osm.org#7]
**Iain R. Learmonth**
Blog: http://iain.learmonth.me/
Feed: http://iain.learmonth.me/tag/planet-osm/rss/

----

**Akshat Tandon**
Hi, I am working on Marble, which is a virtual globe and a member of KDE and OSGeo family, as part of my Google Summer of Code project. As part of the project I am supposed to build tools which convert, simplify, reduce, process OSM data. I plan to write few blog posts about my work and the progress so far. May you add my blog feed http://droftware.github.io/feed.osm.xml to blogs.osm.org so that I can inform people of the OSM community about the project.

----

**Marcos Dione**
I would like to add my blog to blogs.osm.org. It's a 98% technical blog, but mostly around other things I do besides OSM. If you think that would be too much noise, or the policies do not allow it, you can use this feed: http://www.grulic.org.ar/~mdione/glob/tags/openstreetmap/index.atom

If the whole blog is ok, then use this one: http://www.grulic.org.ar/~mdione/glob/index.atom

----
**WeeklyOSM**
I only today discovered blogs.osm.org and was wondering if you could add WeeklyOSM to it? http://www.weeklyosm.eu

**Comment by RobJN** [comment]
Would be good to get Mapillary and a few other organisations too.

Note: May relate to #18 (although given that the blogs of some individuals can include non- or fringe- OSM stuff then I see no difference here - it takes a second to skip an unrelated post).

**Comment by harry-wood** [comment]
I guess @smsm1 plonked multiple old requests in here from somewhere else. Were these emails? Looks like they're quite old requests.

**Iain R. Learmonth** only blogged once about OpenStreetMap back in Dec 2015 (assuming this tag view is working): https://iain.learmonth.me/tags/osm/  

**Akshat Tandon** wrote a series of blog posts about OSM on his site there  http://droftware.github.io ...but none since August 2016

**Marcos Dione** is StyXman. He added _himself_ in the end, back in Mar 2017 https://github.com/gravitystorm/blogs.osm.org/commit/54afa65a20673b20da3a5d837a123b854c50862e

**WeeklyOSM** was added back in 2016 https://github.com/gravitystorm/blogs.osm.org/commit/2663203ff65fa261aa3b853ad8779a165403f49

So on investigation ... that was a whole lot of nothing :-)

Finally @RobJN 's suggestion _"Mapillary and a few other organisations too"_ could be a good one. Let's split out these ideas. I think we could organise this as one "Add blog:X" issue for each blog we want to add. So here's a separate issue for Mapillary: https://github.com/gravitystorm/blogs.osm.org/issues/43

....and this issue we can close.
